### ISSUE TITLE
Haxball headless host colorful and anonymous writing

### ISSUE THREAD

**Issue by SaNaTKaR04** [saviola777/haxball-headless-manager#28]
https://media.discordapp.net/attachments/699014040357175466/711353480467710002/unknown.png?width=400&height=209
How can I do that

**Comment by saviola777** [comment]
By using a custom version of the headless host, which is not supported by the haxball author, and also not explicitly supported by me. There are ways to enable this using a web proxy to inject your own JavaScript files into the headless page, but I have never tried this myself so I can't give you instructions even if I wanted to, sorry.
