### ISSUE TITLE
Add support for accessing HBInit through window object

### ISSUE THREAD

**Issue by flying-aces-hb** [saviola777/haxball-headless-manager#34]
Some room script use `window.HBInit` to access the `HBInit` function, this is currently not supported for HHM plugins or room scripts, but support should be simple to add.

A first idea would be to create a shallow copy of the window object and inject our `HBInit` function, and then pass this window object as a parameter to the function in the context of which the plugins are executed.

Not sure if this works though (can we shadow the window object?) or if there are any problematic side effects.

**Comment by saviola777** [comment]
A quick test showed that shadowing the window object works inside a function context.

**Comment by saviola777** [comment]
This is now implemented.
